### ISSUE TITLE
Проблема с плавной прокруткой

### ISSUE THREAD

**Issue by CoDeWebPro** [aleksanderlamkov/css-normalize#1]
Scroll-behavior не наследуется,  а значит и  плавная прокрутка не будет работать для дочерних элементов с собственной полосой прокрутки

**Comment by aleksanderlamkov** [comment]
Да, но так и задумано. Плавный скролл работает только для всей страницы при клике на якорные ссылки. Ни в каких других ситуациях это свойство использовать и не получится.

**Comment by aleksanderlamkov** [comment]
Да, есть такое. Весьма специфический случай, когда это свойство нужно не для всего `<html>`, но решение с has target из твоего PR мне нравится.
