### ISSUE TITLE
Улучшить отключение анимаций и переходов

### ISSUE THREAD

**Issue by CoDeWebPro** [aleksanderlamkov/css-normalize#3]
Отключить анимации и переходы для псевдоэлементов before и after

**Comment by aleksanderlamkov** [comment]
Готово: https://github.com/aleksanderlamkov/css-normalize/commit/5d43ce7bed241bbb2de83152685bb9b63d8faa1a

**Comment by aleksanderlamkov** [comment]
Готово: https://github.com/aleksanderlamkov/css-normalize/commit/5d43ce7bed241bbb2de83152685bb9b63d8faa1a
