### ISSUE TITLE
Нормализация таблиц

### ISSUE THREAD

**Issue by CoDeWebPro** [aleksanderlamkov/css-normalize#5]
Нормализация таблиц для всех браузеров:
- Свернуть интервал между границами
- Правильный цвет границы таблицы
- Удалите текстовые отступы из содержимого таблицы

**Comment by aleksanderlamkov** [comment]
> * Свернуть интервал между границами

Это про `border-collapse: collapse`?

> * Правильный цвет границы таблицы

Это про `border: solid` для `table {}`? 

> * Удалите текстовые отступы из содержимого таблицы

Это про какие? У `<td>` нет `padding`.

**Comment by CoDeWebPro** [comment]
:where(table) {
  border-collapse: collapse;
  border-color: currentColor;
  text-indent: 0;
}

глючит гит не могу ветку создать в браузере...

**Comment by aleksanderlamkov** [comment]
> text-indent: 0;

Разве он не 0 по умолчанию во всех браузерах? В Chrome и Safari проверил, там по нулям в Computed.

**Comment by CoDeWebPro** [comment]
раньше в Safari наследовался от родителя, сейчас не могу найти в какой версии это было исправлено

**Comment by CoDeWebPro** [comment]
да действительно [2 года назад](https://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css#L220) в WebKit это исправили, думаю это можно уже игнорить
